---
services:
  postgres-db:
    container_name: postgres-db
    env_file:
      - database.env.prod
    image: postgres
    ports:
    - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: webapp
    command:  bash -c 'while !</dev/tcp/postgres-db/5432; do sleep 1; done; gunicorn --bind 0.0.0.0:8000 mainsite.wsgi'
    expose:
      - 8000  # only allow 8000 to other docker services
    volumes:
      - "mainsite:/opt/www/django-apps/mainsite"
      - "static_volume:/opt/www/django-apps/static/"

    env_file:
      - .env.prod
    depends_on:
      - postgres-db
  proxy:
    build:
      ./nginx
    container_name: proxy
    volumes:
      - "mainsite:/opt/www/django-apps/mainsite"
      - "static_volume:/opt/www/django-apps/static/"
      - "nginx_certs:/etc/nginx/certs"
    ports:
    - "8080:80"
    - "8888:443"
    depends_on:
      - webapp

version: "3"
volumes:
  db-data: ~
  mainsite: ~
  static_volume: ~
  nginx_certs: ~
